apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: invoiceninja/invoiceninja
    newTag: alpine-4.5.34
  - name: nginx
    newTag: stable
resources:
- configmap-nginx.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- secrets/configmap-env.yaml
- secrets/secret-env.yaml