apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -v5
namespace: invoiceninja-5
images:
- name: invoiceninja/invoiceninja
  newTag: 5.7.33
resources:
- prod/pvc.yaml
- base
configMapGenerator:
- files:
  - config/in-vhost.conf
  - config/shutdown.sh
  name: config-files
secretGenerator:
- envs:
  - secrets/env.txt
  name: env-secret
generatorOptions:
  disableNameSuffixHash: true
labels:
- includeSelectors: true
  pairs:
    app: invoiceninja-v5
patches:
- path: prod/patch-deployment-app.yaml
- path: prod/patch-deployment-web.yaml
- path: prod/patch-ingress.yaml
