apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: invoiceninja-nfs
  namespace: invoiceninja
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client-ds