apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceninja
spec:
  template:
    spec:
      # nodeSelector:
      #   kubernetes.io/arch: amd64
      containers:
      - name: app
        resources:
          requests:
            cpu: 150m
            memory: 506M
          limits:
            cpu: 2000m
            memory: 1000M
      volumes:
      - name: invoiceninja
        persistentVolumeClaim:
          claimName: invoiceninja-nfs-v5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      # nodeSelector:
      #   kubernetes.io/arch: amd64
      containers:
        - name: web
          resources:
            requests:
              cpu: 15m
              memory: 105M
            limits:
              cpu: 82m
              memory: 105M
      volumes:
      - name: invoiceninja
        persistentVolumeClaim:
          claimName: invoiceninja-nfs-v5