apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: invoiceninja
spec:
  rules:
  - host: racuni.zuraj.com
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 80
  tls:
  - hosts:
    - racuni.zuraj.com
    secretName: racuni.zuraj.com-cert
