apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceninja
spec:
  template:
    spec:
      volumes:
      - name: invoiceninja
        persistentVolumeClaim:
          claimName: invoiceninja-nfs-v5