apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: invoiceninja-v5
images:
  - name: invoiceninja/invoiceninja
    newTag: "5"
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml