apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# nameSuffix: "-5"
commonLabels:
  app: invoiceninja-v5
images:
  - name: invoiceninja/invoiceninja
    newTag: "5"
resources:
  # - configmap-nginx.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # - secrets/configmap-env.yaml
  # - secrets/secret-env.yaml

# generatorOptions:
#   disableNameSuffixHash: true